### ISSUE TITLE
White screen if userID is null

### ISSUE THREAD

**Issue by seedback** [Team-LAMA/watchlist_app#8]
if model.app.userID is null AND model.app.listID is null AND model.signedInInfo.userID is null the screen goes completely white with this concole error:

```
homeController.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'followedUsers')
    at notificationUpdate (homeController.js:10:43)
    at homeView (homeView.js:37:10)
    at updateView (view.js:28:3)
    at updateView (view.js:25:3)
    at view.js:2:1
```

**Comment by seedback** [comment]
This affects only (possibly) homeView
